# Travis requires sudo permissions on this build machine to execute docker commands
sudo: required

# Travis needs to install docker
services:
  - docker

# Travis build docker image with the dev dockerfile (not the production one)
before_install:
  - docker build -t rbotla/react-test -f ./client/Dockerfile.dev ./client

# Run tests on the docker build image. If there more tests you can append to the list of scripts.
script:
  - docker run -e CI=true rbotla/react-test npm test

# After successful completion of tests, build docker images using production dockerfiles and push them to docker hub
after_success:
  - docker build -t rbotla/multi-client ./client
  - docker build -t rbotla/multi-nginx ./nginx
  - docker build -t rbotla/multi-server ./server
  - docker build -t rbotla/multi-worker ./worker
  # Login into DockerHub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push the images to docker hub
  - docker push rbotla/multi-client
  - docker push rbotla/multi-nginx
  - docker push rbotla/multi-server
  - docker push rbotla/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-918700838480"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

language: generic 
